module.exports.descriptors = [
    'Quiet',
    'Spacious',
    'Cozy',
    'Natural',
    'Modern',
    'Historic',
    'Rooftop',
    'Outdoor',
    'Panoramic',
    'Artistic',
    'Scenic',
    'Innovative',
    'Sunny',
    'Shaded',
    'Enclosed',
    'Open',
    'Cultural',
    'Rustic',
    'Tech-Enabled',
    'Elegant'
]

module.exports.places = [
    'Library',
    'Study Hall',
    'Cafeteria',
    'Student Lounge',
    'Bookstore Cafe',
    'Gallery',
    'Garden',
    'Patio',
    'Roof Deck',
    'Auditorium',
    'Lab',
    'Quad',
    'Seminar Room',
    'Athletic Complex',
    'Music Room',
    'Art Studio',
    'Museum',
    'Theater Lobby',
    'Greenhouse',
    'Observatory'
]
